name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Install Bun
        uses: tanaabased/actions/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts
      - name: Run linter
        run: bun run lint
      - name: Export release metadata
        run: |
          echo "SITEMAP_LASTMOD=${{ github.event.release.published_at }}" >> "${GITHUB_ENV}"

      - name: Prepare release
        uses: tanaabased/actions/publish-repo@v1
        with:
          commands: |
            bun run build
            version-injector dist/script.sh --style sh --version "${{ github.event.release.tag_name }}"
            version-injector dist/script.ps1 --style ps1 --version "${{ github.event.release.tag_name }}"
          sync-token: ${{ secrets.TANAAB_COAXIUM_INJECTOR }}
